name: CI

on:
  push:
    tags: [ v* ]

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Release
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 sync . s3://${{ secrets.RELEASE_BUCKET }}/${{ github.event.repository.name }}/${GITHUB_REF##*/} --exclude "*" --include "tf.sh"
